version: '3.8'

services:
  # Initialize VAST DB and Kafka topics
  vast-init-db:
    image: vast-init:latest
    build:
      context: ./vast-init
    env_file: .env
    depends_on: []
    environment:
      - VASTDB_ENDPOINT=${VASTDB_ENDPOINT}
      - VASTDB_ACCESS_KEY=${VASTDB_ACCESS_KEY}
      - VASTDB_SECRET_KEY=${VASTDB_SECRET_KEY}
      - VASTDB_BUCKET=${VASTDB_BUCKET}
      - VASTDB_SCHEMA=${VASTDB_SCHEMA}
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL}
    deploy:
      mode: replicated-job
      replicas: 1
    command: >
      bash -c "
      python setup_vast_tables.py
      "

  vast-init-kafka:
    image: vast-init:latest
    build:
      context: ./vast-init
    env_file: .env
    depends_on: []
    environment:
      - VASTDB_ENDPOINT=${VASTDB_ENDPOINT}
      - VASTDB_ACCESS_KEY=${VASTDB_ACCESS_KEY}
      - VASTDB_SECRET_KEY=${VASTDB_SECRET_KEY}
      - VASTDB_BUCKET=${VASTDB_BUCKET}
      - VASTDB_SCHEMA=${VASTDB_SCHEMA}
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL}
    deploy:
      mode: replicated-job
      replicas: 1
    command: >
      bash -c "
      python setup_vast_topics.py
      "

  # This is our intelligent, pattern-driven generator
  telco-generator:
    image: telco-generator:latest # Use a tagged image for stack deployments
    build:
      context: ./telco-generator
    deploy:
      replicas: 4 # Start with 4 replicas. Scale with 'docker service scale'.
    env_file: .env # Load environment variables from .env file
    environment:
      # These are passed from the .env file
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL}
      - VASTDB_ENDPOINT=${VASTDB_ENDPOINT}
      - VASTDB_ACCESS_KEY=${VASTDB_ACCESS_KEY}
      - VASTDB_SECRET_KEY=${VASTDB_SECRET_KEY}
      - VASTDB_BUCKET=${VASTDB_BUCKET}
      - VASTDB_SCHEMA=${VASTDB_SCHEMA}
      - TOTAL_CELL_TOWERS=${TOTAL_CELL_TOWERS}
      # This magical variable tells each replica its number (e.g., 1, 2, 3, 4)
      # We use this to partition the subscribers.
      - GENERATOR_PARTITION_ID={{.Task.Slot}}
      - TOTAL_PARTITIONS=4 # Must match the number of replicas
    depends_on:
      - vast-init-kafka

  # This service's role is now purely to ingest high-volume analytical data.
  vast-db-sink:
    image: vast-db-sink:latest
    build:
      context: ./vast-db-sink
    deploy:
      replicas: 2 # Scale this based on Kafka topic partitions
    env_file: .env # Load environment variables from .env file
    environment:
      # These are passed from the .env file
      - KAFKA_BROKER_URL=${KAFKA_BROKER_URL}
      - VASTDB_ENDPOINT=${VASTDB_ENDPOINT}
      - VASTDB_ACCESS_KEY=${VASTDB_ACCESS_KEY}
      - VASTDB_SECRET_KEY=${VASTDB_SECRET_KEY}
      - VASTDB_BUCKET=${VASTDB_BUCKET}
      - VASTDB_SCHEMA=${VASTDB_SCHEMA}
    depends_on:
      - vast-init-db
