apiVersion: v1
kind: Service
metadata:
  name: subscriber-simulator-service
  labels:
    app: subscriber-simulator
spec:
  selector:
    app: subscriber-simulator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP # Use ClusterIP for internal communication, or LoadBalancer for external access
